//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AWEAwemeBaseViewController.h"

#import "AWEDetailCommentInputViewDelegate-Protocol.h"
#import "AWEEmoticonKeyboardHelperDelegate-Protocol.h"
#import "AWEUserMessage-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class AWEDetailCommentInputView, AWEEmoticonKeyboardHelper, NSString, UIView;
@protocol AWEIMEmoticonContainerViewProtocol;

@interface AWEAwemeDetailBaseViewController : AWEAwemeBaseViewController <UIGestureRecognizerDelegate, AWEUserMessage, AWEEmoticonKeyboardHelperDelegate, AWEDetailCommentInputViewDelegate>
{
    AWEDetailCommentInputView *_commentInputView;
    UIView *_keyboarMaskView;
    UIView<AWEIMEmoticonContainerViewProtocol> *_emoticonView;
    UIView *_emoticonContainerView;
    AWEEmoticonKeyboardHelper *_emoticonKeyboardHelper;
}

@property(retain, nonatomic) AWEEmoticonKeyboardHelper *emoticonKeyboardHelper; // @synthesize emoticonKeyboardHelper=_emoticonKeyboardHelper;
@property(retain, nonatomic) UIView *emoticonContainerView; // @synthesize emoticonContainerView=_emoticonContainerView;
@property(retain, nonatomic) UIView<AWEIMEmoticonContainerViewProtocol> *emoticonView; // @synthesize emoticonView=_emoticonView;
@property(retain, nonatomic) UIView *keyboarMaskView; // @synthesize keyboarMaskView=_keyboarMaskView;
- (void).cxx_destruct;
- (void)didFinishBindPhone;
- (void)updateCommentInputView;
- (void)setModel:(id)arg1;
- (void)setPureMode:(_Bool)arg1;
- (id)textView;
@property(retain, nonatomic) AWEDetailCommentInputView *commentInputView;
- (struct CGRect)commentInputViewFrameWithoutKeyboard;
- (struct CGRect)commentInputViewFrameWithKeyboardHeight:(double)arg1;
- (void)keyboarMaskViewTapped:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)sendCommentContent;
- (void)createRepost;
- (_Bool)userTappedSendWithContent:(id)arg1;
- (void)emoticonKeyboardSendButtonClicked:(id)arg1;
- (void)growingTextViewDidChange:(id)arg1;
- (_Bool)commentInputViewShouldReturn:(id)arg1;
- (void)reset;
- (void)commentInputViewEmoticonButtonClicked:(id)arg1;
- (_Bool)commentInputViewShouldShowUserPicker:(id)arg1;
- (_Bool)commentInputViewShouldBeginEditing:(id)arg1;
- (void)commentInputView:(id)arg1 didChangeHeightWithDiff:(double)arg2;
- (_Bool)rootViewTapGestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)viewSafeAreaInsetsDidChange;
- (void)layoutSubViews;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

