//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AWEAwemeDeletionMessage-Protocol.h"
#import "AWEAwemeDetailTableViewControllerProtocol-Protocol.h"
#import "AWECommentListInputViewDelegate-Protocol.h"
#import "AWECommentSearchParentViewController-Protocol.h"
#import "AWEModernFullscreenTransitionInnerContextProvider-Protocol.h"
#import "AWEUserMessage-Protocol.h"
#import "AWEZoomTransitionInnerContextProvider-Protocol.h"
#import "BTDRouterViewControllerProtocol-Protocol.h"
#import "HTSAccountMessage-Protocol.h"
#import "IESVisionSearchZoomTransitionInnerContextProvider-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AWEAwemeModel, AWECommentListInputView, AWECommentSearchHelper, AWEDetailBottomView, AWEDiscoverFeedEntranceView, AWEFeedViewedView, AWEListDataController, AWEProgressLoadingView, AWEViewerListDataController, AWEXiGuaCommentInputView, MASConstraint, NSDictionary, NSMutableArray, NSMutableDictionary, NSNumber, NSString, UITableView, UITableViewCell, UIView, UIVisualEffectView;
@protocol AWEAwemeDetailTableViewControllerDelegate, AWEYAMSceneRecordProtocol;

@interface AWEAwemeDetailTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, BTDRouterViewControllerProtocol, AWEUserMessage, AWEAwemeDeletionMessage, HTSAccountMessage, AWEZoomTransitionInnerContextProvider, AWECommentListInputViewDelegate, AWEModernFullscreenTransitionInnerContextProvider, IESVisionSearchZoomTransitionInnerContextProvider, AWECommentSearchParentViewController, AWEAwemeDetailTableViewControllerProtocol>
{
    _Bool _isModernFullScreen;
    _Bool _isUnreadAwemePage;
    _Bool _shouldPreventStartStayTime;
    _Bool _shouldHideMusicInfoView;
    _Bool _showInitialLoading;
    _Bool _isFromDiscovery;
    _Bool _loadPrevious;
    _Bool _slientPreloadBefore;
    _Bool _notDefaultInit;
    _Bool _forbidAutoAdjustFooter;
    _Bool _keepInOutViewConsistent;
    _Bool _isHotPointPanelShow;
    _Bool _isAppearingOnAir;
    _Bool _needPreFetch;
    _Bool _shouldEnablePushSourceTracker;
    _Bool _processingLogin;
    _Bool _hasScrolled;
    _Bool _isViewDidDisappear;
    _Bool _isViewDidAppear;
    _Bool _shouldPreventPause;
    _Bool _shouldPreventTrackStayTime;
    _Bool _preventPersonalPage;
    _Bool _justRefreshed;
    _Bool _lineViewsUpdated;
    _Bool _isFromIM;
    _Bool _isLiveActionTypeChecked;
    _Bool _canClickActionButton;
    id <AWEAwemeDetailTableViewControllerDelegate> _delegate;
    UITableView *_tableView;
    CDUnknownBlockType _dataControllerChangedBlock;
    CDUnknownBlockType _dataControllerLoadmoreBlock;
    CDUnknownBlockType _dataControllerDeleteBlock;
    CDUnknownBlockType _startStayTimeBlock;
    CDUnknownBlockType _trackStayTimeBlock;
    NSString *_originEntryEnterMethod;
    long long _loadMoreStyle;
    NSString *_awemeID;
    NSString *_noMoreDataDescription;
    NSDictionary *_detailBottomInfoDict;
    AWEListDataController *_dataController;
    AWECommentListInputView *_commentInputView;
    UIView *_returnView;
    NSString *_titleInAllFeeds;
    NSString *_reactId;
    double _defaultSeekToTime;
    NSString *_previousPage;
    NSString *_cityInfoString;
    NSDictionary *_logExtraDict;
    NSDictionary *_userTrackAttributes;
    NSDictionary *_logPassback;
    NSString *_referString;
    NSString *_enterFrom;
    NSString *_initialIDs;
    NSString *_pushPassThrouthParam;
    long long _initialIndex;
    AWEDiscoverFeedEntranceView *_discoverEntranceView;
    AWEXiGuaCommentInputView *_xiguaInputView;
    AWEProgressLoadingView *_loadingView;
    AWEAwemeModel *_slideToProfileModel;
    id <AWEYAMSceneRecordProtocol> _scene;
    double _limitedScrollOffsetY;
    NSNumber *_oldOffsetY;
    double _lastContentOffset;
    UIView *_searchContainerView;
    AWECommentSearchHelper *_searchHelper;
    MASConstraint *_commentSearchShow;
    MASConstraint *_commentSearchHide;
    NSMutableArray *_preloadCacheArray;
    NSMutableDictionary *_preloadCacheParam;
    UIView *_operationViewForAdOperationView;
    UITableViewCell *_currentDisplayingCell;
    UIView *_bottomCoverView;
    AWEDetailBottomView *_bottomShootView;
    AWEFeedViewedView *_bottomViewedView;
    AWEViewerListDataController *_viewerListdataController;
    long long _currentIndex;
    UIVisualEffectView *_effectView;
}

+ (void)pigeonToDetailTableViewControllerWithParam:(id)arg1;
+ (id)detailTableViewControllerWithDataController:(id)arg1 initialIndex:(long long)arg2 referString:(id)arg3;
+ (void)__awe__codeRunnerRun_448;
@property(retain, nonatomic) UIVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) AWEViewerListDataController *viewerListdataController; // @synthesize viewerListdataController=_viewerListdataController;
@property(retain, nonatomic) AWEFeedViewedView *bottomViewedView; // @synthesize bottomViewedView=_bottomViewedView;
@property(nonatomic) _Bool canClickActionButton; // @synthesize canClickActionButton=_canClickActionButton;
@property(retain, nonatomic) AWEDetailBottomView *bottomShootView; // @synthesize bottomShootView=_bottomShootView;
@property(retain, nonatomic) UIView *bottomCoverView; // @synthesize bottomCoverView=_bottomCoverView;
@property(nonatomic) __weak UITableViewCell *currentDisplayingCell; // @synthesize currentDisplayingCell=_currentDisplayingCell;
@property(retain, nonatomic) UIView *operationViewForAdOperationView; // @synthesize operationViewForAdOperationView=_operationViewForAdOperationView;
@property(retain, nonatomic) NSMutableDictionary *preloadCacheParam; // @synthesize preloadCacheParam=_preloadCacheParam;
@property(retain, nonatomic) NSMutableArray *preloadCacheArray; // @synthesize preloadCacheArray=_preloadCacheArray;
@property(retain, nonatomic) MASConstraint *commentSearchHide; // @synthesize commentSearchHide=_commentSearchHide;
@property(retain, nonatomic) MASConstraint *commentSearchShow; // @synthesize commentSearchShow=_commentSearchShow;
@property(retain, nonatomic) AWECommentSearchHelper *searchHelper; // @synthesize searchHelper=_searchHelper;
@property(retain, nonatomic) UIView *searchContainerView; // @synthesize searchContainerView=_searchContainerView;
@property(nonatomic) double lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(nonatomic) _Bool isLiveActionTypeChecked; // @synthesize isLiveActionTypeChecked=_isLiveActionTypeChecked;
@property(nonatomic) _Bool isFromIM; // @synthesize isFromIM=_isFromIM;
@property(nonatomic) _Bool lineViewsUpdated; // @synthesize lineViewsUpdated=_lineViewsUpdated;
@property(retain, nonatomic) NSNumber *oldOffsetY; // @synthesize oldOffsetY=_oldOffsetY;
@property(nonatomic) double limitedScrollOffsetY; // @synthesize limitedScrollOffsetY=_limitedScrollOffsetY;
@property(nonatomic) _Bool justRefreshed; // @synthesize justRefreshed=_justRefreshed;
@property(nonatomic) _Bool preventPersonalPage; // @synthesize preventPersonalPage=_preventPersonalPage;
@property(nonatomic) _Bool shouldPreventTrackStayTime; // @synthesize shouldPreventTrackStayTime=_shouldPreventTrackStayTime;
@property(nonatomic) _Bool shouldPreventPause; // @synthesize shouldPreventPause=_shouldPreventPause;
@property(nonatomic) _Bool isViewDidAppear; // @synthesize isViewDidAppear=_isViewDidAppear;
@property(nonatomic) _Bool isViewDidDisappear; // @synthesize isViewDidDisappear=_isViewDidDisappear;
@property(nonatomic) _Bool hasScrolled; // @synthesize hasScrolled=_hasScrolled;
@property(retain, nonatomic) id <AWEYAMSceneRecordProtocol> scene; // @synthesize scene=_scene;
@property(retain, nonatomic) AWEAwemeModel *slideToProfileModel; // @synthesize slideToProfileModel=_slideToProfileModel;
@property(retain, nonatomic) AWEProgressLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) _Bool processingLogin; // @synthesize processingLogin=_processingLogin;
@property(retain, nonatomic) AWEXiGuaCommentInputView *xiguaInputView; // @synthesize xiguaInputView=_xiguaInputView;
@property(retain, nonatomic) AWEDiscoverFeedEntranceView *discoverEntranceView; // @synthesize discoverEntranceView=_discoverEntranceView;
@property(nonatomic) _Bool shouldEnablePushSourceTracker; // @synthesize shouldEnablePushSourceTracker=_shouldEnablePushSourceTracker;
@property(nonatomic) _Bool needPreFetch; // @synthesize needPreFetch=_needPreFetch;
@property(nonatomic) _Bool isAppearingOnAir; // @synthesize isAppearingOnAir=_isAppearingOnAir;
@property(nonatomic) long long initialIndex; // @synthesize initialIndex=_initialIndex;
@property(copy, nonatomic) NSString *pushPassThrouthParam; // @synthesize pushPassThrouthParam=_pushPassThrouthParam;
@property(copy, nonatomic) NSString *initialIDs; // @synthesize initialIDs=_initialIDs;
@property(nonatomic) _Bool isHotPointPanelShow; // @synthesize isHotPointPanelShow=_isHotPointPanelShow;
@property(nonatomic) _Bool keepInOutViewConsistent; // @synthesize keepInOutViewConsistent=_keepInOutViewConsistent;
@property(nonatomic) _Bool forbidAutoAdjustFooter; // @synthesize forbidAutoAdjustFooter=_forbidAutoAdjustFooter;
@property(copy, nonatomic) NSString *enterFrom; // @synthesize enterFrom=_enterFrom;
@property(copy, nonatomic) NSString *referString; // @synthesize referString=_referString;
@property(copy, nonatomic) NSDictionary *logPassback; // @synthesize logPassback=_logPassback;
@property(retain, nonatomic) NSDictionary *userTrackAttributes; // @synthesize userTrackAttributes=_userTrackAttributes;
@property(copy, nonatomic) NSDictionary *logExtraDict; // @synthesize logExtraDict=_logExtraDict;
@property(copy, nonatomic) NSString *cityInfoString; // @synthesize cityInfoString=_cityInfoString;
@property(nonatomic) _Bool notDefaultInit; // @synthesize notDefaultInit=_notDefaultInit;
@property(nonatomic) _Bool slientPreloadBefore; // @synthesize slientPreloadBefore=_slientPreloadBefore;
@property(nonatomic, getter=shouldLoadPrevious) _Bool loadPrevious; // @synthesize loadPrevious=_loadPrevious;
@property(copy, nonatomic) NSString *previousPage; // @synthesize previousPage=_previousPage;
@property(nonatomic) double defaultSeekToTime; // @synthesize defaultSeekToTime=_defaultSeekToTime;
@property(copy, nonatomic) NSString *reactId; // @synthesize reactId=_reactId;
@property(nonatomic) _Bool isFromDiscovery; // @synthesize isFromDiscovery=_isFromDiscovery;
@property(nonatomic) _Bool showInitialLoading; // @synthesize showInitialLoading=_showInitialLoading;
@property(retain, nonatomic) NSString *titleInAllFeeds; // @synthesize titleInAllFeeds=_titleInAllFeeds;
@property(retain, nonatomic) UIView *returnView; // @synthesize returnView=_returnView;
@property(retain, nonatomic) AWECommentListInputView *commentInputView; // @synthesize commentInputView=_commentInputView;
@property(retain, nonatomic) AWEListDataController *dataController; // @synthesize dataController=_dataController;
@property(nonatomic) _Bool shouldHideMusicInfoView; // @synthesize shouldHideMusicInfoView=_shouldHideMusicInfoView;
@property(copy, nonatomic) NSDictionary *detailBottomInfoDict; // @synthesize detailBottomInfoDict=_detailBottomInfoDict;
@property(copy, nonatomic) NSString *noMoreDataDescription; // @synthesize noMoreDataDescription=_noMoreDataDescription;
@property(copy, nonatomic) NSString *awemeID; // @synthesize awemeID=_awemeID;
@property(nonatomic) _Bool shouldPreventStartStayTime; // @synthesize shouldPreventStartStayTime=_shouldPreventStartStayTime;
@property(nonatomic) _Bool isUnreadAwemePage; // @synthesize isUnreadAwemePage=_isUnreadAwemePage;
@property(nonatomic) _Bool isModernFullScreen; // @synthesize isModernFullScreen=_isModernFullScreen;
@property(nonatomic) long long loadMoreStyle; // @synthesize loadMoreStyle=_loadMoreStyle;
@property(copy, nonatomic) NSString *originEntryEnterMethod; // @synthesize originEntryEnterMethod=_originEntryEnterMethod;
@property(copy, nonatomic) CDUnknownBlockType trackStayTimeBlock; // @synthesize trackStayTimeBlock=_trackStayTimeBlock;
@property(copy, nonatomic) CDUnknownBlockType startStayTimeBlock; // @synthesize startStayTimeBlock=_startStayTimeBlock;
@property(copy, nonatomic) CDUnknownBlockType dataControllerDeleteBlock; // @synthesize dataControllerDeleteBlock=_dataControllerDeleteBlock;
@property(copy, nonatomic) CDUnknownBlockType dataControllerLoadmoreBlock; // @synthesize dataControllerLoadmoreBlock=_dataControllerLoadmoreBlock;
@property(copy, nonatomic) CDUnknownBlockType dataControllerChangedBlock; // @synthesize dataControllerChangedBlock=_dataControllerChangedBlock;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <AWEAwemeDetailTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)appendTrackParamsIfNeeded:(id)arg1;
- (void)onScrollBackToIndex:(long long)arg1;
- (void)onScrollWillChangeVideo:(id)arg1 index:(long long)arg2 directTop:(_Bool)arg3;
- (void)onScrollDidScroll:(id)arg1 nextModel:(id)arg2 percentage:(double)arg3;
- (_Bool)needShowCommentInputViewOnScrollingNextAwemeType:(long long)arg1 currentAwemeType:(long long)arg2;
- (_Bool)needHideCommentInputViewOnScrollingNextAwemeType:(long long)arg1 currentAwemeType:(long long)arg2;
- (_Bool)isFromGeneralSearch;
- (void)hideReturnAndCommentViewWhenInitialize;
- (void)hideReturnAndCommentViewIfNeed;
- (id)visibleBulletCells;
- (id)visibleRecommendUserCells;
- (id)visibleLiveCells;
- (id)currentCellConrtoller;
- (id)currentModel;
- (id)visibleDetailCells;
- (_Bool)canSlide;
- (void)p_showTutorialSwipeUpIfNeeded;
- (id)aweui_emptyPageConfigForState:(unsigned long long)arg1;
- (void)aweui_emptyPagePrimaryButtonTapped:(id)arg1;
- (id)awesst_additionalTrackerParams;
- (_Bool)awesst_isVideoPlayViewController;
- (id)awesst_enterFrom;
- (id)awemeModel;
- (void)dismissCommentSearchViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showCommentSearchViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)operationGuideViewTapped;
- (void)handleCloseAdOperationGuideViewNotification:(id)arg1;
- (void)handleShowAdOperationGuideViewNotification:(id)arg1;
- (id)currentLiveRoomID;
- (void)closeWithAnimated:(_Bool)arg1;
- (id)awemeModelWithIndex:(long long)arg1;
- (void)requestImageWithURLArray:(id)arg1 itemID:(id)arg2;
- (void)preloadImageForAweme:(id)arg1;
- (void)preloadCoverImageWithIndexPath:(id)arg1;
- (void)commentInputView:(id)arg1 didChangeHeightWithDiff:(double)arg2;
- (void)growingTextViewDidChange:(id)arg1;
- (void)commentInputViewEmoticonButtonClicked:(id)arg1;
- (_Bool)commentInputViewShouldReturn:(id)arg1;
- (_Bool)commentInputViewShouldBeginEditing:(id)arg1;
- (void)commentInputViewWillHide:(id)arg1 keyboardSize:(struct CGSize)arg2;
- (void)commentInputViewWillShow:(id)arg1 keyboardSize:(struct CGSize)arg2;
- (id)currentDisplayingAweme;
- (id)awe_preferredTransitionProviderClassNameForContext:(id)arg1;
- (void)endFooterHasMore:(_Bool)arg1;
- (void)reloadWithDataController:(id)arg1 initialIndex:(long long)arg2;
- (void)reloadWithInitialIndex:(long long)arg1;
- (void)updateInitialIndex:(long long)arg1;
- (void)reloadDataForDataControllerChange;
- (id)modernTransitionContext;
- (_Bool)modernTransitionItemHasScrolled;
- (long long)modernTransitionItemOffset;
- (long long)zoomTransitionItemOffset;
- (void)videoTopStatusChanged:(id)arg1;
- (void)transition_performCustomActionForSlideDirection:(unsigned long long)arg1 gestureRecognizer:(id)arg2;
- (_Bool)transition_enableCustomActionForSlideDirection:(unsigned long long)arg1 gestureRecognizer:(id)arg2;
- (id)transition_destinatedViewControllerForSlideDirection:(unsigned long long)arg1 gestureRecognizer:(id)arg2;
- (void)transition_didStartTransitionWithContext:(id)arg1;
- (void)didPostAweme:(id)arg1;
- (void)handleCommentShrinkVideo:(id)arg1;
- (void)splashDidDisappear:(id)arg1;
- (void)FTCWindowDidDismiss;
- (void)FTCWindowDidShow;
- (void)_windowDidResignKeyNotification:(id)arg1;
- (void)_windowDidBecomeKeyNotification:(id)arg1;
- (void)showCommentViewAndVideoPlayer;
- (void)showFullVideoPlayerOnScreen;
- (_Bool)isReportMaskShowing;
- (void)playIfActive;
- (void)_onAwemeVideoPlayGuideViewTouched:(id)arg1;
- (void)_appDidBecomeActive:(id)arg1;
- (void)_appWillResignActive:(id)arg1;
- (void)refreshCurrenRecommendCell;
- (void)unlikeUserWithIndex:(long long)arg1;
- (void)removeUserInIndexs:(id)arg1;
- (long long)_findFirstItemWithID:(id)arg1;
- (void)_onAwemeDeleted:(id)arg1;
- (void)onAwemeUnInterestNotification:(id)arg1;
- (void)jumpToNextVideoWithObjectID:(id)arg1;
- (void)commentInputViewUserInteractionOn:(id)arg1;
- (void)handleBroadcastNotification:(id)arg1;
- (void)_onAwemeDeleteNotification:(id)arg1;
- (_Bool)isActive;
- (void)willShowKeyboard:(id)arg1;
- (unsigned long long)_currentVisibleCellIndex;
- (void)_removeNotifications;
- (void)_addNotifications;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)_getModelSafelyForRow:(long long)arg1;
- (void)_doVideoPrefetchCacheSizeTrack:(id)arg1;
- (void)__doVideoPrefetch:(long long)arg1;
- (void)_doVideoPrefetch;
- (void)_cancelVideoPrefetch;
- (void)videoVoteFinished;
- (void)videoDownloadFinished:(id)arg1;
- (void)_onScrollDidEnd;
- (void)updateCommentInputViewAlpha:(double)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (double)_cellHeight;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)updateLineViewsWithModel:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)deleteAwemeWithIDs:(id)arg1;
- (void)_onFollowStatusChanged:(id)arg1 status:(long long)arg2 error:(id)arg3;
- (void)didFinishUnFollowUser:(id)arg1 status:(long long)arg2 error:(id)arg3;
- (void)didFinishFollowUser:(id)arg1 status:(long long)arg2 error:(id)arg3;
- (void)didCancelLogin;
- (void)didFinishLogin;
- (void)willStartLogin;
- (void)willLoginAtPlatform:(unsigned long long)arg1;
- (void)stop;
- (void)pauseLive;
- (void)playLive;
- (void)pause;
- (void)play;
- (void)didMoveToParentViewController:(id)arg1;
- (void)trackBack;
- (void)trackStaytime;
- (void)startTimingForTrack;
- (void)handleAppWillResignActive;
- (void)handleAppBecomeActive;
- (void)_addObervers;
- (void)addDiscoverEntranceView;
- (_Bool)shouldShowDiscoverEntranceView;
- (void)onDiscoverButtonClicked:(id)arg1;
- (void)updateViewerViewAfterDiggChanged:(id)arg1;
- (void)updateBottomViewedWithAwemeID:(id)arg1 statisticsModel:(id)arg2;
- (void)updateCommentInputView:(id)arg1;
- (void)configureXiGuaInputView;
- (_Bool)isFromGeneralSearchOrVideoSearch;
- (double)getStartSeekTime:(id)arg1;
- (void)setFeedColumntypeIfNeeded;
- (void)loadMoreForDiscoverDetailStyle;
- (void)loadMoreForOldStyle;
- (void)loadmore;
- (void)performBlock:(CDUnknownBlockType)arg1;
- (void)loadPrevious:(_Bool)arg1;
- (void)silentSmoothLoadBefore;
- (void)initialFetch;
- (void)initialFetchWithIDs:(id)arg1;
- (void)initialFetchFromIM;
- (void)addLoadPreviousIfNeeded;
- (void)addLoadMoreIfNeeded;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithDataController:(id)arg1 IDs:(id)arg2 initialIndex:(long long)arg3 referString:(id)arg4 logExtraDict:(id)arg5;
- (id)initWithDataController:(id)arg1 IDs:(id)arg2 initialIndex:(long long)arg3 referString:(id)arg4;
- (id)initWithDataController:(id)arg1 initialIndex:(long long)arg2 referString:(id)arg3 enterFrom:(id)arg4 logExtraDict:(id)arg5;
- (id)initWithDataController:(id)arg1 initialIndex:(long long)arg2 referString:(id)arg3 logExtraDict:(id)arg4;
- (id)initWithDataController:(id)arg1 initialIndex:(long long)arg2 referString:(id)arg3;
- (_Bool)configWithRouterParamDict:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end


#import "NSObject-Protocol.h"

@class AWEAwemeModel, NSIndexPath, UITableViewCell, UIViewController;
@protocol AWEAwemeDetailTableViewControllerProtocol;

@protocol AWEAwemeDetailTableViewControllerDelegate <NSObject>

@optional
- (void)detailTableViewControllerWillDisappear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillScrollToNextItem:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillScrollToPreviousItem:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (_Bool)detailTableViewControllerShouldUseFeedImageCache:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 scrollDidEndAtIndexPath:(NSIndexPath *)arg2 model:(AWEAwemeModel *)arg3;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 model:(AWEAwemeModel *)arg4;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 didPauseDisplayingCellWithCurrentPlayingTime:(double)arg2;
- (double)detailTableViewControllerInitialSeekTime:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
@end

