//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "AWEUserMessage-Protocol.h"

@class AWECommentModel, AWECommentPostStateView, AWECommentTranslationLoadingView, AWEInsetsLabel, AWEUserNameLabel, NSString, UIButton, UIImageView, UILabel, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView, YYAnimatedImageView, YYLabel;
@protocol AWECommentPanelCellTranslationDelegate;

@interface AWECommentPanelBaseCell : UITableViewCell <AWEUserMessage>
{
    _Bool _isLikeBtnAnimated;
    AWECommentModel *_commentModel;
    id <AWECommentPanelCellTranslationDelegate> _transInfoDelegate;
    CDUnknownBlockType _likeButtonTappedBlock;
    CDUnknownBlockType _handleLongPressBlock;
    CDUnknownBlockType _retryPostBlock;
    CDUnknownBlockType _avatarOrNameTappedBlock;
    NSString *_referString;
    NSString *_cityInfoString;
    NSString *_itemUserID;
    long long _sceneType;
    UITapGestureRecognizer *_reloadStickerGR;
    AWECommentModel *_mainComment;
    AWECommentModel *_quotedCommentModel;
    UIView *_highlightBackgroundView;
    UIImageView *_avatarView;
    UIView *_avatarBorderView;
    AWEUserNameLabel *_nameLabel;
    YYLabel *_commentLabel;
    UIButton *_likeButton;
    UILabel *_likesLabel;
    YYAnimatedImageView *_stickerImgView;
    UILabel *_timeLabel;
    AWECommentTranslationLoadingView *_translationLoadingView;
    AWECommentPostStateView *_postStateView;
    UILabel *_likedByCreatorLabel;
    AWEInsetsLabel *_authorTagLabel;
    AWEInsetsLabel *_followerOrNearbyTagLabel;
    AWEInsetsLabel *_relationTagLabel;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    id _generator;
    UIView *_lineView;
}

+ (id)identifier;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) id generator; // @synthesize generator=_generator;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) AWEInsetsLabel *relationTagLabel; // @synthesize relationTagLabel=_relationTagLabel;
@property(retain, nonatomic) AWEInsetsLabel *followerOrNearbyTagLabel; // @synthesize followerOrNearbyTagLabel=_followerOrNearbyTagLabel;
@property(retain, nonatomic) AWEInsetsLabel *authorTagLabel; // @synthesize authorTagLabel=_authorTagLabel;
@property(retain, nonatomic) UILabel *likedByCreatorLabel; // @synthesize likedByCreatorLabel=_likedByCreatorLabel;
@property(retain, nonatomic) AWECommentPostStateView *postStateView; // @synthesize postStateView=_postStateView;
@property(retain, nonatomic) AWECommentTranslationLoadingView *translationLoadingView; // @synthesize translationLoadingView=_translationLoadingView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) YYAnimatedImageView *stickerImgView; // @synthesize stickerImgView=_stickerImgView;
@property(retain, nonatomic) UILabel *likesLabel; // @synthesize likesLabel=_likesLabel;
@property(retain, nonatomic) UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) YYLabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) AWEUserNameLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *avatarBorderView; // @synthesize avatarBorderView=_avatarBorderView;
@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *highlightBackgroundView; // @synthesize highlightBackgroundView=_highlightBackgroundView;
@property(retain, nonatomic) AWECommentModel *quotedCommentModel; // @synthesize quotedCommentModel=_quotedCommentModel;
@property(retain, nonatomic) AWECommentModel *mainComment; // @synthesize mainComment=_mainComment;
@property(retain, nonatomic) UITapGestureRecognizer *reloadStickerGR; // @synthesize reloadStickerGR=_reloadStickerGR;
@property(nonatomic) _Bool isLikeBtnAnimated; // @synthesize isLikeBtnAnimated=_isLikeBtnAnimated;
@property(nonatomic) long long sceneType; // @synthesize sceneType=_sceneType;
@property(copy, nonatomic) NSString *itemUserID; // @synthesize itemUserID=_itemUserID;
@property(copy, nonatomic) NSString *cityInfoString; // @synthesize cityInfoString=_cityInfoString;
@property(copy, nonatomic) NSString *referString; // @synthesize referString=_referString;
@property(copy, nonatomic) CDUnknownBlockType avatarOrNameTappedBlock; // @synthesize avatarOrNameTappedBlock=_avatarOrNameTappedBlock;
@property(copy, nonatomic) CDUnknownBlockType retryPostBlock; // @synthesize retryPostBlock=_retryPostBlock;
@property(copy, nonatomic) CDUnknownBlockType handleLongPressBlock; // @synthesize handleLongPressBlock=_handleLongPressBlock;
@property(copy, nonatomic) CDUnknownBlockType likeButtonTappedBlock; // @synthesize likeButtonTappedBlock=_likeButtonTappedBlock;
@property(nonatomic) __weak id <AWECommentPanelCellTranslationDelegate> transInfoDelegate; // @synthesize transInfoDelegate=_transInfoDelegate;
@property(retain, nonatomic) AWECommentModel *commentModel; // @synthesize commentModel=_commentModel;
- (void).cxx_destruct;
- (void)didFinishSetRemarkWithUser:(id)arg1;
- (void)didFinishBlockUser:(id)arg1 status:(long long)arg2;
- (void)didFinishUnFollowUser:(id)arg1 status:(long long)arg2 error:(id)arg3;
- (void)p_reloadSticker;
- (void)updateLikedByCreator;
- (void)updateLikeStateWithAnimation:(_Bool)arg1;
- (void)trackAdForFeedWithAwemeModel:(id)arg1 refer:(id)arg2;
- (void)trackAdForSearchWithAwemeModel:(id)arg1 didOpenAppStore:(_Bool)arg2;
- (void)openProfileOrLandingPage:(id)arg1;
- (void)_executeTapAlphaAnimation:(id)arg1 reverse:(_Bool)arg2;
- (_Bool)checkNeedAnimation:(id)arg1 reverse:(_Bool)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)clearAnimatedImageBuffer;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)p_addSticker;
- (void)p_showStickerLongPressMenu;
- (void)resetLikesLabel;
- (void)relationTagLabelTapped:(id)arg1;
- (void)linkHighlightTapped:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)likeButtonTapped;
- (void)commentUserTapped:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)updateNameLabel;
- (_Bool)appendStickerAttachment;
- (_Bool)showTimestampAfterComment;
- (_Bool)needLongPressGesture;
- (_Bool)shouldShowLikedByCreatorLabel;
- (_Bool)canShowLikedByCreatorLabel;
- (_Bool)showLikesButton;
- (_Bool)showLikesLabel;
- (void)fixDiggCount;
- (id)displayTimeText;
- (id)translatedContent;
- (id)displayAttrContent;
- (id)displayContent;
- (unsigned long long)translationStatus;
- (id)authorName;
- (void)highlight;
- (void)setupUI;
- (void)prepareForReuse;
- (void)configWithComment:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

