//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AWECommentPanelBaseCell.h"

@class AWECommentPanelQuotedView;

@interface AWECommentPanelCell : AWECommentPanelBaseCell
{
    AWECommentPanelQuotedView *_quotedView;
}

+ (id)identifier;
@property(retain, nonatomic) AWECommentPanelQuotedView *quotedView; // @synthesize quotedView=_quotedView;
- (void).cxx_destruct;
- (void)didFinishSetRemarkWithUser:(id)arg1;
- (void)didFinishBlockUser:(id)arg1 status:(long long)arg2;
- (void)didFinishUnFollowUser:(id)arg1 status:(long long)arg2 error:(id)arg3;
- (void)layoutSubviews;
- (void)configWithComment:(id)arg1;
- (void)setupUI;

@end

