//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "AWEFeedTableViewCellProtocol-Protocol.h"

@class AWEFeedCellViewController, NSString, UIViewController;

@interface AWEFeedViewCell : UITableViewCell <AWEFeedTableViewCellProtocol>
{
    long long _indexPath;
    AWEFeedCellViewController *_viewController;
    UIViewController *_parentVC;
    NSString *_referString;
}

@property(copy, nonatomic) NSString *referString; // @synthesize referString=_referString;
@property(nonatomic) __weak UIViewController *parentVC; // @synthesize parentVC=_parentVC;
@property(retain, nonatomic) AWEFeedCellViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) long long indexPath; // @synthesize indexPath=_indexPath;
- (void).cxx_destruct;
- (_Bool)isLikeUserPanelShowing;
- (_Bool)isPoliticalMaskViewShowing;
- (_Bool)isCommentPanelShowing;
- (void)resetRefreshFlag;
- (_Bool)isScrolledAutomatically;
- (void)setIsScrolledAutomatically:(_Bool)arg1;
- (void)_removeChildVC;
- (void)_addChildVC;
- (double)currentPlaybackTime;
- (void)prepareForReuse;
- (void)reset;
- (void)pause;
- (void)stop;
- (void)play;
- (void)prepareForDisplay;
- (void)configureWithModel:(id)arg1;
- (void)configWithModel:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

