//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MXSegmentedPagerController.h"

#import "AWEMusicDetailCollectionViewScrollDelegate-Protocol.h"
#import "AWEShareMessage-Protocol.h"
#import "AWEUILoadingProvider-Protocol.h"
#import "BTDRouterViewControllerProtocol-Protocol.h"

@class AWEBizUIBubble, AWEButton, AWECollectionButton, AWEEnhancedCollectionButton, AWEMusicDetailCollectionViewController, AWEMusicDetailHeaderView, AWEMusicModel, AWEUITextLoadingView, NSDictionary, NSLock, NSMutableArray, NSString, UIButton, UILabel, UIScrollView;

@interface AWEMusicDetailViewController : MXSegmentedPagerController <BTDRouterViewControllerProtocol, AWEMusicDetailCollectionViewScrollDelegate, AWEShareMessage, AWEUILoadingProvider>
{
    _Bool _alreadyHandleMusicEntryPlan;
    _Bool _collectionViewControlerPreloaded;
    _Bool _isFromExternal;
    _Bool _needReloadSegmentManually;
    NSString *_musicID;
    AWEMusicModel *_model;
    NSMutableArray *_awemeList;
    NSString *_groupID;
    NSString *_authorID;
    NSString *_level;
    NSString *_enterFromPageString;
    NSString *_stickers;
    AWEMusicDetailHeaderView *_headerView;
    AWEMusicDetailCollectionViewController *_awemeCollectionViewController;
    UIScrollView *_contentScrollView;
    UILabel *_navigationTitleLabel;
    UIButton *_actionButton;
    AWEButton *_shareBtn;
    AWEButton *_backBtn;
    AWECollectionButton *_collectionBtn;
    AWEEnhancedCollectionButton *_enhancedCollectBtn;
    UIButton *_musicPlanEntryButton;
    NSLock *_collectionLock;
    unsigned long long _sourceVCType;
    NSString *_searchType;
    AWEUITextLoadingView *_loadingView;
    NSString *_platformName;
    NSString *_platformMusicID;
    NSDictionary *_searchLogPassback;
    NSString *_previousPage;
    AWEBizUIBubble *_favoriteHintBubble;
}

+ (void)__awe__codeRunnerRun_1332;
@property(nonatomic) __weak AWEBizUIBubble *favoriteHintBubble; // @synthesize favoriteHintBubble=_favoriteHintBubble;
@property(copy, nonatomic) NSString *previousPage; // @synthesize previousPage=_previousPage;
@property(copy, nonatomic) NSDictionary *searchLogPassback; // @synthesize searchLogPassback=_searchLogPassback;
@property(nonatomic) _Bool needReloadSegmentManually; // @synthesize needReloadSegmentManually=_needReloadSegmentManually;
@property(nonatomic) _Bool isFromExternal; // @synthesize isFromExternal=_isFromExternal;
@property(copy, nonatomic) NSString *platformMusicID; // @synthesize platformMusicID=_platformMusicID;
@property(copy, nonatomic) NSString *platformName; // @synthesize platformName=_platformName;
@property(nonatomic) _Bool collectionViewControlerPreloaded; // @synthesize collectionViewControlerPreloaded=_collectionViewControlerPreloaded;
@property(nonatomic) _Bool alreadyHandleMusicEntryPlan; // @synthesize alreadyHandleMusicEntryPlan=_alreadyHandleMusicEntryPlan;
@property(retain, nonatomic) AWEUITextLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) NSString *searchType; // @synthesize searchType=_searchType;
@property(nonatomic) unsigned long long sourceVCType; // @synthesize sourceVCType=_sourceVCType;
@property(retain, nonatomic) NSLock *collectionLock; // @synthesize collectionLock=_collectionLock;
@property(retain, nonatomic) UIButton *musicPlanEntryButton; // @synthesize musicPlanEntryButton=_musicPlanEntryButton;
@property(retain, nonatomic) AWEEnhancedCollectionButton *enhancedCollectBtn; // @synthesize enhancedCollectBtn=_enhancedCollectBtn;
@property(retain, nonatomic) AWECollectionButton *collectionBtn; // @synthesize collectionBtn=_collectionBtn;
@property(retain, nonatomic) AWEButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) AWEButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UILabel *navigationTitleLabel; // @synthesize navigationTitleLabel=_navigationTitleLabel;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(retain, nonatomic) AWEMusicDetailCollectionViewController *awemeCollectionViewController; // @synthesize awemeCollectionViewController=_awemeCollectionViewController;
@property(retain, nonatomic) AWEMusicDetailHeaderView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) NSString *stickers; // @synthesize stickers=_stickers;
@property(retain, nonatomic) NSString *enterFromPageString; // @synthesize enterFromPageString=_enterFromPageString;
@property(retain, nonatomic) NSString *level; // @synthesize level=_level;
@property(retain, nonatomic) NSString *authorID; // @synthesize authorID=_authorID;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain, nonatomic) NSMutableArray *awemeList; // @synthesize awemeList=_awemeList;
@property(retain, nonatomic) AWEMusicModel *model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *musicID; // @synthesize musicID=_musicID;
- (void).cxx_destruct;
- (void)p_trackUnavailableWithStatus:(id)arg1;
- (id)loadingViewContainerView;
- (void)aweui_emptyPagePrimaryButtonTapped:(id)arg1;
- (id)awesst_enterFrom;
- (void)shareFinishedWithType:(long long)arg1 succeed:(_Bool)arg2;
- (void)shareWithType:(long long)arg1 context:(id)arg2 targetType:(unsigned long long)arg3 targetID:(id)arg4;
- (id)segmentedPager:(id)arg1 viewControllerForPageAtIndex:(long long)arg2;
- (_Bool)isValidMusicID;
- (long long)numberOfPagesInSegmentedPager:(id)arg1;
- (double)heightForSegmentedControlInSegmentedPager:(id)arg1;
- (void)segmentedPager:(id)arg1 didEndDraggingWithParallaxHeader:(id)arg2;
- (void)segmentedPager:(id)arg1 didSelectViewWithIndex:(long long)arg2;
- (void)segmentedPager:(id)arg1 didScrollWithParallaxHeader:(id)arg2;
- (double)adjustFooterHeight;
- (void)onScrollDown;
- (void)onScrollUp;
- (void)goToActivityPage;
- (void)playMusicPlanGuideSpringAnimation;
- (void)playMusicPlanGuideAnimation;
- (void)ownerViewClick:(id)arg1;
- (void)ownerArrowClick:(id)arg1;
- (void)_onActionButtonClicked_IMP:(id)arg1;
- (void)onActionButtonClicked:(id)arg1;
- (void)dismissActionButton;
- (void)showActionButton;
- (void)buildActionButtonAndFovoriteButtonIfNeeded;
- (void)_onShareButtonClicked_IMP:(id)arg1;
- (void)onShareBtnClicked:(id)arg1;
- (void)removeFavoriteHint;
- (void)_collect;
- (void)_onCollectionBtnClicked_IMP:(id)arg1;
- (void)onCollectionBtnClicked:(id)arg1;
- (void)addMusicPlanEntryButton;
- (void)addNavigationView;
- (_Bool)shouldShowMusicPlanEntry:(id)arg1;
- (void)musicCollectedStatusChanged:(id)arg1;
- (void)reloadMusicDetail:(id)arg1;
- (void)reloadMusicDetail;
- (void)didMoveToParentViewController:(id)arg1;
- (void)resetCollectionBtnAndLine;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)preloadDetailData;
- (void)setupUI;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (_Bool)configWithRouterParamDict:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

