//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "AWEProfileHeaderExtraViewControllerDelegate-Protocol.h"
#import "AWETranslationLoadingViewDelegate-Protocol.h"

@class AWEBillboardLabel, AWEProfileActivityLinkModel, AWEProfileBindedAppView, AWEProfileHeaderActionController, AWEProfileHeaderExtraViewController, AWEProfileShopView, AWEProfileSocialStatisticView, AWEProfileTopVideoHelper, AWEProfileTopVideoViewController, AWETranslationLoadingView, AWEUserActivityView, AWEUserDetailHeaderBadgeButton, AWEUserProfileRecommendView, LOTAnimationView, NSString, UIButton, UIImageView, UILabel, YYAnimatedImageView;
@protocol AWEFeedLiveMarkViewProtocol, AWEHeaderViewActionDelegate;

@interface AWEProfileHeaderView : UIView <AWEProfileHeaderExtraViewControllerDelegate, AWETranslationLoadingViewDelegate>
{
    _Bool _isUserFetched;
    _Bool _needTrackStoreEntranceAfterFetchUser;
    _Bool _isRecommendViewShow;
    _Bool _isFirstTimeViewDidLoad;
    id <AWEHeaderViewActionDelegate> _delegate;
    AWEProfileActivityLinkModel *_linkModel;
    AWEProfileHeaderActionController *_actionController;
    UIView *_containerView;
    YYAnimatedImageView *_avatarView;
    UIButton *_avatarEditButton;
    UIImageView *_avatarDecorationView;
    LOTAnimationView *_playAnimationView;
    AWEBillboardLabel *_nameLabel;
    UIButton *_nameEditButton;
    UILabel *_introLabel;
    UILabel *_starAtlasGuideLabel;
    AWETranslationLoadingView *_loadingView;
    UIView *_sepView;
    AWEProfileSocialStatisticView *_socialStatisticView;
    AWEUserDetailHeaderBadgeButton *_verificationBtn;
    AWEProfileShopView *_shopView;
    UIView *_tabView;
    UIView *_recommendView;
    AWEProfileHeaderExtraViewController *_extraViewController;
    AWEUserActivityView *_userActivityView;
    AWEProfileBindedAppView *_bindedAppView;
    UIView *_challengeView;
    UIView *_bottomView;
    AWEUserProfileRecommendView *_userProfileRecommendView;
    UIView<AWEFeedLiveMarkViewProtocol> *_avatarMarkView;
    UIView<AWEFeedLiveMarkViewProtocol> *_avatarSmallMarkView;
    UIView *_wishBannerView;
    UILabel *_idPrefixLabel;
    UILabel *_idLabel;
    AWEProfileTopVideoHelper *_topVideoHelper;
    AWEProfileTopVideoViewController *_topVideoViewController;
}

@property(retain, nonatomic) AWEProfileTopVideoViewController *topVideoViewController; // @synthesize topVideoViewController=_topVideoViewController;
@property(retain, nonatomic) AWEProfileTopVideoHelper *topVideoHelper; // @synthesize topVideoHelper=_topVideoHelper;
@property(retain, nonatomic) UILabel *idLabel; // @synthesize idLabel=_idLabel;
@property(retain, nonatomic) UILabel *idPrefixLabel; // @synthesize idPrefixLabel=_idPrefixLabel;
@property(retain, nonatomic) UIView *wishBannerView; // @synthesize wishBannerView=_wishBannerView;
@property(retain, nonatomic) UIView<AWEFeedLiveMarkViewProtocol> *avatarSmallMarkView; // @synthesize avatarSmallMarkView=_avatarSmallMarkView;
@property(retain, nonatomic) UIView<AWEFeedLiveMarkViewProtocol> *avatarMarkView; // @synthesize avatarMarkView=_avatarMarkView;
@property(retain, nonatomic) AWEUserProfileRecommendView *userProfileRecommendView; // @synthesize userProfileRecommendView=_userProfileRecommendView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *challengeView; // @synthesize challengeView=_challengeView;
@property(retain, nonatomic) AWEProfileBindedAppView *bindedAppView; // @synthesize bindedAppView=_bindedAppView;
@property(retain, nonatomic) AWEUserActivityView *userActivityView; // @synthesize userActivityView=_userActivityView;
@property(retain, nonatomic) AWEProfileHeaderExtraViewController *extraViewController; // @synthesize extraViewController=_extraViewController;
@property(retain, nonatomic) UIView *recommendView; // @synthesize recommendView=_recommendView;
@property(retain, nonatomic) UIView *tabView; // @synthesize tabView=_tabView;
@property(retain, nonatomic) AWEProfileShopView *shopView; // @synthesize shopView=_shopView;
@property(retain, nonatomic) AWEUserDetailHeaderBadgeButton *verificationBtn; // @synthesize verificationBtn=_verificationBtn;
@property(retain, nonatomic) AWEProfileSocialStatisticView *socialStatisticView; // @synthesize socialStatisticView=_socialStatisticView;
@property(retain, nonatomic) UIView *sepView; // @synthesize sepView=_sepView;
@property(retain, nonatomic) AWETranslationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UILabel *starAtlasGuideLabel; // @synthesize starAtlasGuideLabel=_starAtlasGuideLabel;
@property(retain, nonatomic) UILabel *introLabel; // @synthesize introLabel=_introLabel;
@property(retain, nonatomic) UIButton *nameEditButton; // @synthesize nameEditButton=_nameEditButton;
@property(retain, nonatomic) AWEBillboardLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) LOTAnimationView *playAnimationView; // @synthesize playAnimationView=_playAnimationView;
@property(retain, nonatomic) UIImageView *avatarDecorationView; // @synthesize avatarDecorationView=_avatarDecorationView;
@property(retain, nonatomic) UIButton *avatarEditButton; // @synthesize avatarEditButton=_avatarEditButton;
@property(retain, nonatomic) YYAnimatedImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) _Bool isFirstTimeViewDidLoad; // @synthesize isFirstTimeViewDidLoad=_isFirstTimeViewDidLoad;
@property(nonatomic) _Bool isRecommendViewShow; // @synthesize isRecommendViewShow=_isRecommendViewShow;
@property(retain, nonatomic) AWEProfileHeaderActionController *actionController; // @synthesize actionController=_actionController;
@property(nonatomic) _Bool needTrackStoreEntranceAfterFetchUser; // @synthesize needTrackStoreEntranceAfterFetchUser=_needTrackStoreEntranceAfterFetchUser;
@property(retain, nonatomic) AWEProfileActivityLinkModel *linkModel; // @synthesize linkModel=_linkModel;
@property(nonatomic) __weak id <AWEHeaderViewActionDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isUserFetched; // @synthesize isUserFetched=_isUserFetched;
- (void).cxx_destruct;
- (void)idLabelTapped;
- (void)translationLoadingView:(id)arg1 requestTranslationStatus:(_Bool)arg2;
- (void)hideRecommendViewAfterUnfollow;
- (void)scrollViewDidEndDragingWithOffset:(struct CGPoint)arg1;
- (void)scrollViewDidScrollWithOffset:(struct CGPoint)arg1;
- (void)showRecommendViewAfterFollow;
- (void)recommendBtnClicked;
- (void)updateNavigationSlidingButtonView:(long long)arg1;
- (void)updateFansLabel;
- (void)constructTranspondProfileCoverArray;
- (_Bool)isLinkModelChanged:(id)arg1;
- (void)enterVideoFullScreen;
- (double)topVideoViewHeight;
- (double)topVideoViewWidth;
- (void)nameEditButtonTapped;
- (void)updateBottomViewLayout;
- (void)resetErrorStory;
- (void)dismissLoadingAnimation:(_Bool)arg1 task:(id)arg2;
- (void)showLoadingAnimation;
- (double)signatureTop;
- (void)openActivityPage;
- (void)showProfileInfoCompletionAnimation;
- (void)updateProfileCompletion:(float)arg1 hidePercentWhenCompleted:(_Bool)arg2;
- (void)updateShopView;
- (id)awe_hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)updateChallengeView:(id)arg1;
- (void)stopMaskViewAnimation;
- (void)startMaskViewAnimation;
- (void)liveViewPlay;
- (void)updateSocialLinkView;
- (void)hideNewGoodsHint;
- (id)avatarInHeaderView;
- (void)adjustAlpha:(double)arg1;
- (void)updateAvatarBorder;
- (void)showOrHideRecommendView:(_Bool)arg1;
- (void)animateAvatarViewLayerWithShowRecommendView:(_Bool)arg1 duration:(double)arg2;
- (void)updateIntroLabelWithFollowStatus:(long long)arg1;
- (void)updateNameLabel;
- (void)handleTapOnContent:(id)arg1;
- (double)headerViewHeight;
- (void)updateHeaderViewWithLinkModel:(id)arg1;
- (void)configWithUser:(id)arg1 isLogSent:(_Bool)arg2;
- (id)initWithIsCurrentUser:(_Bool)arg1 fromHomepage:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

