//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AWEHeaderViewActionDelegate-Protocol.h"
#import "AWEUserMessage-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class AWEAwemeModel, AWEProfileActivityLinkModel, AWEProfileHeaderView, AWEProfileTopVideoHelper, AWEUserModel, NSDictionary, NSString, UIView;
@protocol AWECompanyChallengeViewController, AWENewYearUserWishControllerProtocol, AWEProfileHeaderViewControllerDelegate, AWEUserRecommendViewControllerProtocol;

@interface AWEProfileHeaderViewController : UIViewController <AWEHeaderViewActionDelegate, AWEUserMessage, UIGestureRecognizerDelegate>
{
    _Bool _isUserInfoFetched;
    _Bool _fromHomePage;
    _Bool _isRecommendAnimation;
    _Bool _needRefreshUI;
    _Bool _needForceRefreshHeaderView;
    AWEUserModel *_user;
    AWEAwemeModel *_model;
    id <AWEProfileHeaderViewControllerDelegate> _delegate;
    AWEProfileHeaderView *_profileHeaderView;
    NSDictionary *_trackerParam;
    AWEProfileTopVideoHelper *_topVideoHelper;
    UIViewController<AWEUserRecommendViewControllerProtocol> *_userRecommendVC;
    UIViewController<AWECompanyChallengeViewController> *_corpChallengeVC;
    id <AWENewYearUserWishControllerProtocol> _wishController;
    long long _profileType;
    NSString *_userID;
    UIView *_contentView;
    AWEProfileActivityLinkModel *_linkModel;
}

@property(retain, nonatomic) AWEProfileActivityLinkModel *linkModel; // @synthesize linkModel=_linkModel;
@property(nonatomic) _Bool needForceRefreshHeaderView; // @synthesize needForceRefreshHeaderView=_needForceRefreshHeaderView;
@property(nonatomic) _Bool needRefreshUI; // @synthesize needRefreshUI=_needRefreshUI;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) _Bool isRecommendAnimation; // @synthesize isRecommendAnimation=_isRecommendAnimation;
@property(copy, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(nonatomic) _Bool fromHomePage; // @synthesize fromHomePage=_fromHomePage;
@property(nonatomic) long long profileType; // @synthesize profileType=_profileType;
@property(retain, nonatomic) id <AWENewYearUserWishControllerProtocol> wishController; // @synthesize wishController=_wishController;
@property(retain, nonatomic) UIViewController<AWECompanyChallengeViewController> *corpChallengeVC; // @synthesize corpChallengeVC=_corpChallengeVC;
@property(retain, nonatomic) UIViewController<AWEUserRecommendViewControllerProtocol> *userRecommendVC; // @synthesize userRecommendVC=_userRecommendVC;
@property(retain, nonatomic) AWEProfileTopVideoHelper *topVideoHelper; // @synthesize topVideoHelper=_topVideoHelper;
@property(retain, nonatomic) NSDictionary *trackerParam; // @synthesize trackerParam=_trackerParam;
@property(nonatomic) _Bool isUserInfoFetched; // @synthesize isUserInfoFetched=_isUserInfoFetched;
@property(retain, nonatomic) AWEProfileHeaderView *profileHeaderView; // @synthesize profileHeaderView=_profileHeaderView;
@property(nonatomic) __weak id <AWEProfileHeaderViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AWEAwemeModel *model; // @synthesize model=_model;
@property(retain, nonatomic) AWEUserModel *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)trackLiveShowEvent;
- (void)didFinishBlockUser:(id)arg1 status:(long long)arg2;
- (void)didFinishSetRemarkWithUser:(id)arg1;
- (void)topVideoDidFinishedLeaveFullScreen;
- (void)topVideoLeaveFullScreenWithAnimation:(_Bool)arg1;
- (void)topVideoWillLeaveFullScreen;
- (void)topVideoDidFinishedEnterFullScreen;
- (void)topVideoEnterFullScreenWithAnimation:(_Bool)arg1 fullScreenTopOffsetY:(double)arg2;
- (void)scrollOffsetYLessThanTopVideoEntryOffsetY;
- (void)topVideoWillEnterFullScreen;
- (void)updateNavBtnAlpha:(double)arg1;
- (void)updateHeaderHeight;
- (void)showBubbleViewWithFollowStatus:(long long)arg1 reportBtn:(id)arg2;
- (void)hideRecommendViewAfterUnfollow;
- (void)showRecommendViewAfterFollow;
- (void)updateNavigationSlidingButtonView:(long long)arg1;
- (void)updateCompletionInfoIfNeed:(id)arg1 avatarURL:(id)arg2;
- (void)updatedTranslationClicked;
- (void)recommendBtnClicked;
- (void)changeSlidingTabWithLocation:(struct CGPoint)arg1;
- (void)constructTranspondProfileCoverArray;
- (void)p_recommendViewAnimationIfShow:(_Bool)arg1;
- (void)p_recommendDataErrorWithToast:(id)arg1;
- (void)p_closeRecommendView;
- (void)p_showRecommendView:(_Bool)arg1;
- (_Bool)p_addUserRecommendControllerIfNeeded;
- (void)p_recommendViewDidChange:(_Bool)arg1 hideWhenLessThenFiveResults:(_Bool)arg2;
- (void)handleBroadcastNotification:(id)arg1;
- (void)liveBlockAudienceNotication:(id)arg1;
- (void)p_checkAvatarForCompleteProfileBubble:(id)arg1 url:(id)arg2;
- (Class)p_getHeaderViewClass;
- (void)p_removeObervers;
- (void)p_addObervers;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)scrollViewDidEndDragingWithOffset:(struct CGPoint)arg1;
- (void)scrollViewDidScrollWithOffset:(struct CGPoint)arg1;
- (void)resetErrorStory;
- (void)dismissLoadingAnimation:(_Bool)arg1 task:(id)arg2;
- (void)showLoadingAnimation;
- (void)handleCompanyBannerInteraction;
- (void)showBannerView;
- (void)changeCoverViewAlpha:(double)arg1 relativeWithDefaultValue:(_Bool)arg2;
- (void)updateCompanyTopCover:(double)arg1;
- (void)showProfileInfoCompletionAnimation;
- (void)updateProfileCompletion:(float)arg1 hidePercentWhenCompleted:(_Bool)arg2;
- (void)updateAvatarBorder;
- (void)updateAddBtnYellowPointCount:(long long)arg1;
- (void)hideNewGoodsHint;
- (void)needTrackStoreEntranceAfterFetchUser:(_Bool)arg1;
- (void)updateHeaderViewHeightWithLinkModel:(id)arg1;
- (void)sendMsgBtnClicked:(id)arg1;
- (void)updateIntroLabelWithFollowStatus:(long long)arg1;
- (void)updateNameLabel;
- (void)updateRelationWithFollowStatus:(long long)arg1 followerStatus:(long long)arg2 animated:(_Bool)arg3;
- (long long)currentFollowStatus;
- (id)avatarInHeaderView;
- (void)reportBtnClicked:(id)arg1;
- (void)relationBtnClicked:(id)arg1;
- (void)refreshHeaderFrame:(struct CGRect)arg1;
- (struct CGRect)currentFrameOfHeaderView;
- (void)removeAllChildVC;
- (void)updateWishBannerIfNeeded:(_Bool)arg1;
- (void)updateChallengeViewIfNeeded;
- (void)configWithUser:(id)arg1 isLogSent:(_Bool)arg2;
- (void)configWithUser:(id)arg1;
- (void)updateUser:(id)arg1;
- (void)replaceHeaderView;
- (_Bool)needReplaceHeaderView;
- (void)setForceRefreshHeaderView;
- (void)refreshAlphaForHeaderView:(double)arg1;
- (double)introLabelTopOfHeaderView;
- (double)headerViewHeight;
- (void)handleTapOnContent:(id)arg1;
- (void)addTapGestureOnContentViewForHeaderView:(id)arg1;
- (void)setTabbarViewForHeaderView:(id)arg1;
- (id)initWithUserID:(id)arg1 profileType:(long long)arg2 fromHomePage:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

